### ISSUE TITLE
Pip install fails on pyhcl

### ISSUE THREAD

**Issue by argherna** [ddriddle/terragrunt-source#1]
When running `pip3 install terragrunt-source`, the output is:

```Collecting terragrunt-source
  Downloading https://files.pythonhosted.org/packages/89/23/d92298c0f67562d4462cf357c9f2071babdb85a8cadfc5910c55b3a99149/terragrunt_source-0.1.0a3-py2.py3-none-any.whl
Collecting pyhcl (from terragrunt-source)
  Downloading https://files.pythonhosted.org/packages/d1/6f/1d5516d307eb728dd64892694d33a6a1b14869c96ca55b5bf42bf1e40bcb/pyhcl-0.3.10.tar.gz
Collecting ply==3.10 (from pyhcl->terragrunt-source)
  Downloading https://files.pythonhosted.org/packages/ce/3d/1f9ca69192025046f02a02ffc61bfbac2731aab06325a218370fd93e18df/ply-3.10.tar.gz (150kB)
    100% |████████████████████████████████| 153kB 5.0MB/s 
Building wheels for collected packages: pyhcl, ply
  Running setup.py bdist_wheel for pyhcl ... error
  Complete output from command /usr/local/opt/python/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/7q/pr4jm3x501l6_1fd4dgmzj4r0000gp/T/pip-install-p_88d_pt/pyhcl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/7q/pr4jm3x501l6_1fd4dgmzj4r0000gp/T/pip-wheel-8nkbpp8w --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  Generating parse table...
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/7q/pr4jm3x501l6_1fd4dgmzj4r0000gp/T/pip-install-p_88d_pt/pyhcl/setup.py", line 96, in <module>
      "Topic :: Text Processing"
    File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/7q/pr4jm3x501l6_1fd4dgmzj4r0000gp/T/pip-install-p_88d_pt/pyhcl/setup.py", line 37, in run
      self.execute(_pre_install, (), msg="Generating parse table...")
    File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 335, in execute
      util.execute(func, args, msg, dry_run=self.dry_run)
    File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/util.py", line 301, in execute
      func(*args)
    File "/private/var/folders/7q/pr4jm3x501l6_1fd4dgmzj4r0000gp/T/pip-install-p_88d_pt/pyhcl/setup.py", line 30, in _pre_install
      import hcl
    File "/private/var/folders/7q/pr4jm3x501l6_1fd4dgmzj4r0000gp/T/pip-install-p_88d_pt/pyhcl/src/hcl/__init__.py", line 1, in <module>
      from .api import dumps, load, loads
    File "/private/var/folders/7q/pr4jm3x501l6_1fd4dgmzj4r0000gp/T/pip-install-p_88d_pt/pyhcl/src/hcl/api.py", line 3, in <module>
      from .parser import HclParser
    File "/private/var/folders/7q/pr4jm3x501l6_1fd4dgmzj4r0000gp/T/pip-install-p_88d_pt/pyhcl/src/hcl/parser.py", line 5, in <module>
      from .lexer import Lexer
    File "/private/var/folders/7q/pr4jm3x501l6_1fd4dgmzj4r0000gp/T/pip-install-p_88d_pt/pyhcl/src/hcl/lexer.py", line 3, in <module>
      import ply.lex as lex
  ModuleNotFoundError: No module named 'ply'
  
  ----------------------------------------
  Failed building wheel for pyhcl
  Running setup.py clean for pyhcl
  Running setup.py bdist_wheel for ply ... done
  Stored in directory: /Users/agherna/Library/Caches/pip/wheels/ee/a7/25/452e4339cd14b61b79869cd34f1d2bb9b9e6c8847421cea784
Successfully built ply
Failed to build pyhcl
Installing collected packages: ply, pyhcl, terragrunt-source
  Running setup.py install for pyhcl ... done
Successfully installed ply-3.10 pyhcl-0.3.10 terragrunt-source-0.1.0a3
```

**Comment by argherna** [comment]
When running `pip3 install terragrunt-source` a second time, this is the output:

```
Requirement already satisfied: terragrunt-source in /usr/local/lib/python3.6/site-packages (0.1.0a3)
Requirement already satisfied: pyhcl in /usr/local/lib/python3.6/site-packages (from terragrunt-source) (0.3.10)
Requirement already satisfied: ply==3.10 in /usr/local/lib/python3.6/site-packages (from pyhcl->terragrunt-source) (3.10)
```
